apiVersion: v1
kind: Service
metadata:
    name: "testdos-311a"
    labels:
        app: "testdos-311a"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testdos-311a"