on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tural.azurecr.io
        username: ${{ secrets.acr_tural_username }}
        password: ${{ secrets.acr_tural_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t tural.azurecr.io/testdos:${{ github.sha }} --label dockerfile-path=dockerfile
        docker push tural.azurecr.io/testdos:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testdos_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep test-dosb054 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace test-dosb054`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: test-dosb054
        container-registry-url: tural.azurecr.io
        container-registry-username: ${{ secrets.acr_tural_username }}
        container-registry-password: ${{ secrets.acr_tural_password }}
        secret-name: testdosdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: test-dosb054
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          tural.azurecr.io/testdos:${{ github.sha }}
        imagepullsecrets: |
          testdosdockerauth
